apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: apod-log-from-web
  labels:
    kubernetes.courselabs.co: network-policy
spec:
  podSelector:
    matchLabels:
      app: apod-log

  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: apod-web
    ports:
    - port: api

  egress: []  # deny all