apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job
  labels:
    co.courselabs.k8s: jobs
    app: pi-one    
spec:
  template:
    spec:
      containers:
        - name: pi
          image: kiamol/ch05-pi
          command: ["dotnet", "Pi.Web.dll", "-m", "console", "-dp", "50"]
      restartPolicy: Never
