apiVersion: v1
kind: Service
metadata:
  name: whoami-np
  labels:
    co.courselabs.k8sfun: productionizing
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 8010
      targetPort: http
      nodePort: 30010
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-lb
  labels:
    co.courselabs.k8sfun: productionizing
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 8010
      targetPort: http
  type: LoadBalancer