apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    co.courselabs.k8sfun: productionizing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 65534
        runAsGroup: 3000
      containers:
        - name: app
          image: sixeyed/whoami:21.04
          command: ["/app/whoami", "-port", "5000"]
          env:
            - name: WHOAMI_MODE
              value: q
          ports:
            - containerPort: 5000
              name: http
          resources:
            limits:
              cpu: 250m
            requests:
              cpu: 125m
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
              add:
                - net_bind_service