apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurable
  labels: 
    co.courselabs.k8sfun: productionizing
spec:
  selector:
    matchLabels:
      app: configurable
  template:
    metadata:
      labels:
        app: configurable
    spec:
      containers:
        - name: app
          image: sixeyed/configurable:21.04
          env:
            - name: Configurable__FailAfterCallCount
              value: "3"
