apiVersion: v1
kind: ConfigMap
metadata:
  name: configurable-env
  labels: 
    k8s-fundamentals: part-2
    app: configurable
data:
  Configurable__Release: from-configmap
  Configurable__Extra: from-configmap