apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web
  namespace: pi
spec:
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web
        cpu: mid
    spec:
      containers:
        - image: sixeyed/pi:2002
          command: ["dotnet", "Pi.Web.dll", "-m", "web"]
          name: pi-web
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 2500m
              memory: 500Mi
            limits:
              cpu: 2500m
              memory: 500Mi
