apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-cleanup
  namespace: default
  labels:
    co.courselabs.k8sfun: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-cleanup-role
  labels:
    co.courselabs.k8sfun: jobs
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["delete", "get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-cleanup-role-binding
  labels:
    co.courselabs.k8sfun: jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-cleanup-role
subjects:
  - kind: ServiceAccount
    name: job-cleanup
    namespace: default