apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job-one-failing
  labels:
    co.courselabs.k8sfun: jobs
spec:
  template:
    spec:
      containers:
        - name: pi
          image: kiamol/ch05-pi
          command: ["donet", "Pi.Web.dll", "-m", "console", "-dp", "50"]
      restartPolicy: OnFailure