apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    app: mysql-operator
  name: mysqlclusters.mysql.presslabs.org
  annotations:
    helm.sh/hook: crd-install
spec:
  group: mysql.presslabs.org
  names:
    kind: MysqlCluster
    plural: mysqlclusters
    shortNames:
    - mysql
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.readyNodes
    status: {}
  versions: 
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                secretName:
                  type: string
                image:
                  type: string
      additionalPrinterColumns:
      - jsonPath: .status.conditions[?(@.type == "Ready")].status
        description: The cluster status
        name: Ready
        type: string
      - jsonPath: .spec.replicas
        description: The number of desired nodes
        name: Replicas
        type: integer
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
