apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    co.courselabs.k8sfun: statefulsets
spec:
  ports:
    - port: 8040
      targetPort: 80
  selector:
    app: nginx-statefulset
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    co.courselabs.k8sfun: statefulsets
spec:
  ports:
    - port: 8040
      targetPort: 80
      nodePort: 30040
  selector:
    app: nginx-statefulset
  type: NodePort