apiVersion: v1
kind: PersistentVolume
metadata:
  name: pi-proxy-pv
  labels:
    app: pi-proxy
    co.courselabs.k8s: persistentvolumes
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: /volumes/pi-proxy
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: k8sfun
            operator: Exists