apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default
  labels:
    co.courselabs.k8sfun: ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-internal
            port: 
              name: http