apiVersion: v1
kind: Service
metadata:
  name: nginx-internal
  labels:
    co.courselabs.k8sfun: statefulsets
spec:
  ports:
    - port: 8030
      targetPort: 80
  selector:
    app: nginx-statefulset
  clusterIP: None