apiVersion: v1
kind: Service
metadata:
  name: simple-proxy-internal
  labels:
    co.courselabs.k8sfun: statefulsets
spec:
  ports:
    - port: 8030
      targetPort: 80
  selector:
    app: simple-proxy
  clusterIP: None