apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-proxy-pvc
  labels:
    co.courselabs.k8s: persistentvolumes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi