apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader 
  labels:
    co.courselabs.k8sfun: rbac
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]