# service
servicePort: 8020
serviceType: NodePort
serviceNodePort: 30820

# deployment
replicaCount: 2
serverImage: docker.io/sixeyed/whoami-lab:21.09-6 #docker.io/sixeyed/whoami-lab:21.09-1
serverMode: q

# registry
privateImageRegistry: false
registrySecretName: none