apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  labels:
    co.courselabs.k8sfun: rbac
spec:
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: kiamol/ch03-sleep