name: Image Builds

on:
  push:
    paths:
      - ".github/workflows/image-builds.yaml"
      - "src/**"
  schedule:
    - cron: "0 2 * * 6"

jobs:
  docker-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - working-directory: ./src
        run: |
          docker-compose build 
          docker-compose push 