apiVersion: v1
kind: Service
metadata:
  name: products-db
  labels:
    co.courselabs.k8sfun: hackathon
    app: widgetario
spec:
  ports:
    - port: 5432
      targetPort: postgres
  selector:
    app: widgetario
    component: products-db
  type: ClusterIP